# Generated by Django 4.2.5 on 2023-09-14 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tv_show', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='films',
            options={'verbose_name': 'Премьеру', 'verbose_name_plural': 'Премьеры'},
        ),
        migrations.AddField(
            model_name='films',
            name='director',
            field=models.CharField(max_length=100, null=True, verbose_name='Укажите директора'),
        ),
        migrations.AlterField(
            model_name='films',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Укажите описание фильма'),
        ),
    ]
